# Generated by Django 5.2.6 on 2025-09-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('cos_email', models.EmailField(max_length=254)),
                ('dop', models.DateField()),
            ],
        ),
    ]
